# Changes here will be overwritten by Copier
_commit: 1a45ad8
_src_path: gh:audivir/copier-template
author_email: pypi@audivir.de
author_name: Tim Hörmann
description: Rust-accelerated Tanimoto similarity search over RDKit Morgan fingerprints.
github_org: audivir
project_name: smiles-fp
project_slug: smiles_fp
project_type: pyo3
publishable: true
